name: flutter_application_1
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_svg: ^2.2.0
  flutter_screenutil: ^5.9.3
  z: ^0.1.0
  dartz: ^0.10.1
  dio: ^5.8.0+1
  image_picker: ^1.2.0
  shared_preferences: ^2.0.18
  flutter_bloc: ^9.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Lexend_Deca
      fonts:
        - asset: assets/fonts/Lexend_Deca/LexendDeca-Thin.ttf
          weight: 100
        - asset: assets/fonts/Lexend_Deca/LexendDeca-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Lexend_Deca/LexendDeca-Light.ttf
          weight: 300
        - asset: assets/fonts/Lexend_Deca/LexendDeca-Regular.ttf
          weight: 400
        - asset: assets/fonts/Lexend_Deca/LexendDeca-Medium.ttf
          weight: 500
        - asset: assets/fonts/Lexend_Deca/LexendDeca-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Lexend_Deca/LexendDeca-Bold.ttf
          weight: 700
        - asset: assets/fonts/Lexend_Deca/LexendDeca-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Lexend_Deca/LexendDeca-Black.ttf
          weight: 900